grails-app/domain/com/youniversity/core/app/Application.groovy
package com.youniversity.core.app

class Application {
    String name
    String displayedName
    String runPath
    boolean widgetable
    String widgetRunPath

    static constraints = {
        name nullable:false, blank:false, unique:true
        runPath nullable:false, blank:false
        displayedName nullable:true
        widgetRunPath nullable:true, validator: { val, obj ->
            !obj.widgetable || obj.widgetRunPath
        }
    }
}

grails-app/controllers/com/youniversity/core/app/ApplicationController.groovy
package com.youniversity.core.app



import grails.transaction.*
import static org.springframework.http.HttpStatus.*
import grails.converters.JSON
import com.youniversity.core.AuthenticationController

@Transactional(readOnly = true)
class ApplicationController extends AuthenticationController {

    def springSecurityService
    def authenticationService

    def permissions = [
            "/application/index":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod": [
                            "ROLE_USER_MEMBER":"truth"
                    ]
            ],
            "/application/run/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod": [
                            "ROLE_USER_MEMBER":"truth"
                    ]
            ],
            "/application/runWidget/**":["configAttribute":"ROLE_USER_MEMBER"],
            "/application/get-all-apps":["configAttribute":"IS_AUTHENTICATED_ANONYMOUSLY"]
    ]


    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Application.list(params), model:[applicationInstanceCount: Application.count()]
    }

    def show(Application applicationInstance) {
        respond applicationInstance
    }

    def create() {        
        respond new Application(params)
    }

    @Transactional
    def save(Application applicationInstance) {
        if(applicationInstance.hasErrors()) {
            respond applicationInstance.errors, view:'create'
        }
        else {
            applicationInstance.save flush:true
            request.withFormat {
                form {
                    springSecurityService.clearCachedRequestmaps()
                    flash.message = message(code: 'default.created.message', args: [message(code: 'applicationInstance.label', default: 'Application'), applicationInstance.id])
                    redirect applicationInstance
                }
                '*' { respond applicationInstance, [status: CREATED] }
            }
        }
    }

    def run(String appName) {
        def app=Application.findByName(appName)
        if(!app || !app.runPath)        {
            render(view:"appNotFound",model:[appName:appName])
            return
        }
        redirect(url: "/${app?.runPath}")
    }

    def runWidget(String appName) {
        def app=Application.findByName(appName)
        if(!app || !app.widgetable || !app.widgetRunPath)        {
            render text: g.message([code:"youniversity.core.widget.notFound",args:[appName]])
            return
        }
        redirect(url: "/${app?.widgetRunPath}")
    }

    def getAllApps()    {
        def apps = Application.list()
        def response = []

        apps.each{
            response << ["displayedName":it.displayedName,"name":it.name, "widgetable": it.widgetable]
        }

        render response as JSON
    }

    def edit(Application applicationInstance) { 
        respond applicationInstance  
    }

    @Transactional
    def update(Application applicationInstance) {
        if(applicationInstance == null) {
            render status:404
        }
        else if(applicationInstance.hasErrors()) {
            respond applicationInstance.errors, view:'edit'
        }
        else {
            applicationInstance.save flush:true
            request.withFormat {
                form {
                    springSecurityService.clearCachedRequestmaps()
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'Application.label', default: 'Application'), applicationInstance.id])
                    redirect applicationInstance 
                }
                '*'{ respond applicationInstance, [status: OK] }
            }
        }        
    }

    @Transactional
    def delete(Application applicationInstance) {
        if(applicationInstance) {
            applicationInstance.delete flush:true
            request.withFormat {
                form { 
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'Application.label', default: 'Application'), applicationInstance.id])
                    redirect action:"index", method:"GET" 
                }
                '*'{ render status: NO_CONTENT }
            }                
        }
        else {
            render status: NOT_FOUND
        }
    }
}

grails-app/controllers/com/youniversity/core/app/FavouriteAppController.groovy
package com.youniversity.core.app

import grails.transaction.*
import com.youniversity.core.user.User

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class FavouriteAppController {
    def springSecurityService

    def permissions =[
            "/favourite-app/index":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/create":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/save/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/edit":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/update/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/delete/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/show/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/list":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/add/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/add-widget/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/remove/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/remove-widget/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ]
    ]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond FavouriteApp.list(params), model:[favouriteAppInstanceCount: FavouriteApp.count()]
    }

    def show(FavouriteApp favouriteAppInstance) {
        respond favouriteAppInstance
    }

    def create() {
        respond new FavouriteApp(params)
    }

    @Transactional
    def add(Integer id) {
        Application app = Application.findById(id)
        new FavouriteApp(application: app, user: springSecurityService.getCurrentUser(), widget:false).save()
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def addWidget(Integer id) {
        Application app = Application.findById(id)
        new FavouriteApp(application: app, user: springSecurityService.getCurrentUser(), widget:true).save()
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def remove(Integer id)  {
        Application app = Application.findById(id)
        User user = User.findById(1)
        FavouriteApp fav = FavouriteApp.findByApplicationAndUserAndWidget(app,user,false)
        fav.delete(flush:true)
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def removeWidget(Integer id)  {
        Application app = Application.findById(id)
        User user = User.findById(1)
        FavouriteApp fav = FavouriteApp.findByApplicationAndUserAndWidget(app,user,true)
        fav.delete(flush:true)
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def save(FavouriteApp favouriteAppInstance) {
        if(favouriteAppInstance.hasErrors()) {
            respond favouriteAppInstance.errors, view:'create'
        }
        else {
            favouriteAppInstance.save flush:true
            request.withFormat {
                form { 
                    flash.message = message(code: 'default.created.message', args: [message(code: 'favouriteAppInstance.label', default: 'FavouriteApp'), favouriteAppInstance.id])
                    redirect favouriteAppInstance
                }
                '*' { respond favouriteAppInstance, [status: CREATED] }
            }
        }
    }


    def edit(FavouriteApp favouriteAppInstance) { 
        respond favouriteAppInstance  
    }

    @Transactional
    def update(FavouriteApp favouriteAppInstance) {
        if(favouriteAppInstance == null) {
            render status:404
        }
        else if(favouriteAppInstance.hasErrors()) {
            respond favouriteAppInstance.errors, view:'edit'
        }
        else {
            favouriteAppInstance.save flush:true
            request.withFormat {
                form { 
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'FavouriteApp.label', default: 'FavouriteApp'), favouriteAppInstance.id])
                    redirect favouriteAppInstance 
                }
                '*'{ respond favouriteAppInstance, [status: OK] }
            }
        }        
    }

    @Transactional
    def delete(FavouriteApp favouriteAppInstance) {
        if(favouriteAppInstance) {
            favouriteAppInstance.delete flush:true
            request.withFormat {
                form { 
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'FavouriteApp.label', default: 'FavouriteApp'), favouriteAppInstance.id])
                    redirect action:"index", method:"GET" 
                }
                '*'{ render status: NO_CONTENT }
            }                
        }
        else {
            render status: NOT_FOUND
        }
    }
}

grails-app/views/application/_form.gsp
<%@ page import="com.youniversity.core.app.Application" %>



<div class="fieldcontain ${hasErrors(bean: applicationInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="application.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${applicationInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: applicationInstance, field: 'runPath', 'error')} required">
	<label for="runPath">
		<g:message code="application.runPath.label" default="Run Path" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="runPath" required="" value="${applicationInstance?.runPath}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: applicationInstance, field: 'displayedName', 'error')} ">
	<label for="displayedName">
		<g:message code="application.displayedName.label" default="Displayed Name" />
		
	</label>
	<g:textField name="displayedName" value="${applicationInstance?.displayedName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: applicationInstance, field: 'widgetable', 'error')} ">
	<label for="widgetable">
		<g:message code="application.widgetable.label" default="Widgetable" />
		
	</label>
	<g:checkBox name="widgetable" value="${applicationInstance?.widgetable}" />
</div>

<div class="fieldcontain ${hasErrors(bean: applicationInstance, field: 'widgetRunPath', 'error')} ">
	<label for="widgetRunPath">
		<g:message code="application.widgetRunPath.label" default="Widget Run Path" />
		
	</label>
	<g:textField name="widgetRunPath" value="${applicationInstance?.widgetRunPath}"/>
</div>

grails-app/views/application/appNotFound.gsp
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'application.label', default: 'Application')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<h1><g:message code=""  args="${[params.appName]}" /></h1>
</body>
</html>

grails-app/views/application/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'application.label', default: 'Application')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-application" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-application" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${applicationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${applicationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:applicationInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/application/edit.gsp
<%@ page import="com.youniversity.core.app.Application" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'application.label', default: 'Application')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-application" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-application" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${applicationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${applicationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:applicationInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${applicationInstance?.version}" />				
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/application/index.gsp
<%@ page import="com.youniversity.core.app.FavouriteApp; com.youniversity.core.app.Application" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'application.label', default: 'Application')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-application" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-application" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<g:sortableColumn property="name" title="${message(code: 'application.name.label', default: 'Name')}" />

						<g:sortableColumn property="runPath" title="${message(code: 'application.runPath.label', default: 'Run Path')}" />

						<g:sortableColumn property="displayedName" title="${message(code: 'application.displayedName.label', default: 'Displayed Name')}" />

						<g:sortableColumn property="widgetable" title="${message(code: 'application.widgetable.label', default: 'Widgetable')}" />

						<g:sortableColumn property="widgetRunPath" title="${message(code: 'application.widgetRunPath.label', default: 'Widget Run Path')}" />

					</tr>
				</thead>
				<tbody>
				<g:each in="${applicationInstanceList}" status="i" var="applicationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td><g:link action="show" id="${applicationInstance.id}">${fieldValue(bean: applicationInstance, field: "name")}</g:link></td>

						<td>${fieldValue(bean: applicationInstance, field: "runPath")}</td>

						<td>${fieldValue(bean: applicationInstance, field: "displayedName")}</td>

						<td><g:formatBoolean boolean="${applicationInstance.widgetable}" /></td>

						<td>${fieldValue(bean: applicationInstance, field: "widgetRunPath")}</td>

                        <g:if test="${FavouriteApp.findByApplicationAndWidget(applicationInstance,false)}" >
                            <td><g:link id="${applicationInstance.id}" action="remove" controller="favouriteApp">Remove</g:link></td>
                        </g:if>
                        <g:else>
                            <td>
                                 <g:link id="${applicationInstance.id}" action="add" controller="favouriteApp">Add</g:link>
                            </td>
                        </g:else>
                        <g:if test="${applicationInstance.widgetable}">
                        <g:if test="${FavouriteApp.findByApplicationAndWidget(applicationInstance,true)}" >
                            <td><g:link id="${applicationInstance.id}" action="removeWidget" controller="favouriteApp">Remove</g:link></td>
                        </g:if>
                        <g:else>
                            <td>
                                <g:link id="${applicationInstance.id}" action="addWidget" controller="favouriteApp">Add</g:link>
                            </td>
                        </g:else>
                        </g:if>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${applicationInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/application/show.gsp
<%@ page import="com.youniversity.core.app.Application" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'application.label', default: 'Application')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-application" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-application" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list application">
			
				<g:if test="${applicationInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="application.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${applicationInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${applicationInstance?.runPath}">
				<li class="fieldcontain">
					<span id="runPath-label" class="property-label"><g:message code="application.runPath.label" default="Run Path" /></span>
					
						<span class="property-value" aria-labelledby="runPath-label"><g:fieldValue bean="${applicationInstance}" field="runPath"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${applicationInstance?.displayedName}">
				<li class="fieldcontain">
					<span id="displayedName-label" class="property-label"><g:message code="application.displayedName.label" default="Displayed Name" /></span>
					
						<span class="property-value" aria-labelledby="displayedName-label"><g:fieldValue bean="${applicationInstance}" field="displayedName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${applicationInstance?.widgetable}">
				<li class="fieldcontain">
					<span id="widgetable-label" class="property-label"><g:message code="application.widgetable.label" default="Widgetable" /></span>
					
						<span class="property-value" aria-labelledby="widgetable-label"><g:formatBoolean boolean="${applicationInstance?.widgetable}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${applicationInstance?.widgetRunPath}">
				<li class="fieldcontain">
					<span id="widgetRunPath-label" class="property-label"><g:message code="application.widgetRunPath.label" default="Widget Run Path" /></span>
					
						<span class="property-value" aria-labelledby="widgetRunPath-label"><g:fieldValue bean="${applicationInstance}" field="widgetRunPath"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:applicationInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${applicationInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>