grails-app/domain/com/youniversity/core/user/Permission.groovy
package com.youniversity.core.user

import com.youniversity.core.app.Application
class Permission {
    String url
    String configAttribute
    Application application
    Map<String, Closure> authMethod

    static mapping = {
        cache true
    }

    static constraints = {
        url blank: false, unique: true
        configAttribute blank: false
        authMethod nullable: true
    }
}

grails-app/controllers/com/youniversity/core/user/PermissionController.groovy
package com.youniversity.core.user



import grails.transaction.*
import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class PermissionController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def permissions = [
            "/permission/index":["configAttribute":"ROLE_USER_MEMBER"]
    ]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Permission.list(params), model: [permissionInstanceCount: Permission.count()]
    }

    def show(Permission permissionInstance) {
        respond permissionInstance
    }

    def create() {
        respond new Permission(params)
    }

    @Transactional
    def save(Permission permissionInstance) {
        if (permissionInstance.hasErrors()) {
            respond permissionInstance.errors, view: 'create'
        } else {
            permissionInstance.save flush: true
            request.withFormat {
                form {
                    flash.message = message(code: 'default.created.message', args: [message(code: 'permissionInstance.label', default: 'Permission'), permissionInstance.id])
                    redirect permissionInstance
                }
                '*' { respond permissionInstance, [status: CREATED] }
            }
        }
    }

    def edit(Permission permissionInstance) {
        respond permissionInstance
    }

    @Transactional
    def update(Permission permissionInstance) {
        if (permissionInstance == null) {
            render status: 404
        } else if (permissionInstance.hasErrors()) {
            respond permissionInstance.errors, view: 'edit'
        } else {
            permissionInstance.save flush: true
            request.withFormat {
                form {
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'Permission.label', default: 'Permission'), permissionInstance.id])
                    redirect permissionInstance
                }
                '*' { respond permissionInstance, [status: OK] }
            }
        }
    }

    @Transactional
    def delete(Permission permissionInstance) {
        if (permissionInstance) {
            permissionInstance.delete flush: true
            request.withFormat {
                form {
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'Permission.label', default: 'Permission'), permissionInstance.id])
                    redirect action: "index", method: "GET"
                }
                '*' { render status: NO_CONTENT }
            }
        } else {
            render status: NOT_FOUND
        }
    }
}

grails-app/views/permission/_form.gsp
<%@ page import="com.youniversity.core.user.Permission" %>



<div class="fieldcontain ${hasErrors(bean: permissionInstance, field: 'url', 'error')} required">
	<label for="url">
		<g:message code="permission.url.label" default="Url" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="url" required="" value="${permissionInstance?.url}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: permissionInstance, field: 'configAttribute', 'error')} required">
	<label for="configAttribute">
		<g:message code="permission.configAttribute.label" default="Config Attribute" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="configAttribute" required="" value="${permissionInstance?.configAttribute}"/>
</div>


<div class="fieldcontain ${hasErrors(bean: permissionInstance, field: 'application', 'error')} required">
	<label for="application">
		<g:message code="permission.application.label" default="Application" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="application" name="application.id" from="${com.youniversity.core.app.Application.list()}" optionKey="id" required="" value="${permissionInstance?.application?.id}" class="many-to-one"/>
</div>

grails-app/views/permission/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'permission.label', default: 'Permission')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-permission" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-permission" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${permissionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${permissionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:permissionInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/permission/edit.gsp
<%@ page import="com.youniversity.core.user.Permission" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'permission.label', default: 'Permission')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-permission" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-permission" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${permissionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${permissionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:permissionInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${permissionInstance?.version}" />				
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/permission/index.gsp
<%@ page import="com.youniversity.core.user.Permission" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'permission.label', default: 'Permission')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-permission" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-permission" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="url" title="${message(code: 'permission.url.label', default: 'Url')}" />
					
						<g:sortableColumn property="configAttribute" title="${message(code: 'permission.configAttribute.label', default: 'Config Attribute')}" />
					
						<th><g:message code="permission.application.label" default="Application" /></th>
					
					</tr>
				</thead>
				<tbody>
                <g:each in="${permissionInstanceList}" status="i" var="permissionInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td><g:link action="show" id="${permissionInstance.id}">${fieldValue(bean: permissionInstance, field: "url")}</g:link></td>
					
						<td>${fieldValue(bean: permissionInstance, field: "configAttribute")}</td>
					
						<td>${fieldValue(bean: permissionInstance, field: "application")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${permissionInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/permission/show.gsp
<%@ page import="com.youniversity.core.user.Permission" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'permission.label', default: 'Permission')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-permission" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-permission" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list permission">
			
				<g:if test="${permissionInstance?.url}">
				<li class="fieldcontain">
					<span id="url-label" class="property-label"><g:message code="permission.url.label" default="Url" /></span>
					
						<span class="property-value" aria-labelledby="url-label"><g:fieldValue bean="${permissionInstance}" field="url"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${permissionInstance?.configAttribute}">
				<li class="fieldcontain">
					<span id="configAttribute-label" class="property-label"><g:message code="permission.configAttribute.label" default="Config Attribute" /></span>
					
						<span class="property-value" aria-labelledby="configAttribute-label"><g:fieldValue bean="${permissionInstance}" field="configAttribute"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${permissionInstance?.groupRoles}">
				<li class="fieldcontain">
					<span id="groupRoles-label" class="property-label"><g:message code="permission.groupRoles.label" default="Group Roles" /></span>
					
						<g:each in="${permissionInstance.groupRoles}" var="g">
						<span class="property-value" aria-labelledby="groupRoles-label"><g:link controller="groupRole" action="show" id="${g.id}">${g?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${permissionInstance?.application}">
				<li class="fieldcontain">
					<span id="application-label" class="property-label"><g:message code="permission.application.label" default="Application" /></span>
					
						<span class="property-value" aria-labelledby="application-label"><g:link controller="application" action="show" id="${permissionInstance?.application?.id}">${permissionInstance?.application?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:permissionInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${permissionInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>