Chat/grails-app/domain/com/youniversity/apps/chat/MessageHistory.groovy
package com.youniversity.apps.chat

class MessageHistory {

    static constraints = {
    }
}

Chat/grails-app/controllers/com/youniversity/apps/chat/MessageHistoryController.groovy
package com.youniversity.apps.chat



import grails.transaction.*
import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class MessageHistoryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond MessageHistory.list(params), model: [messageHistoryCount: MessageHistory.count()]
    }

    def show(MessageHistory messageHistory) {
        respond messageHistory
    }

    def create() {
        respond new MessageHistory(params)
    }

    @Transactional
    def save(MessageHistory messageHistory) {
        if (messageHistory.hasErrors()) {
            respond messageHistory.errors, view: 'create'
        } else {
            messageHistory.save flush: true
            request.withFormat {
                form {
                    flash.message = message(code: 'default.created.message', args: [message(code: 'messageHistory.label', default: 'MessageHistory'), messageHistory.id])
                    redirect messageHistory
                }
                '*' { respond messageHistory, [status: CREATED] }
            }
        }
    }

    def edit(MessageHistory messageHistory) {
        respond messageHistory
    }

    @Transactional
    def update(MessageHistory messageHistory) {
        if (messageHistory == null) {
            render status: 404
        } else if (messageHistory.hasErrors()) {
            respond messageHistory.errors, view: 'edit'
        } else {
            messageHistory.save flush: true
            request.withFormat {
                form {
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'MessageHistory.label', default: 'MessageHistory'), messageHistory.id])
                    redirect messageHistory
                }
                '*' { respond messageHistory, [status: OK] }
            }
        }
    }

    @Transactional
    def delete(MessageHistory messageHistory) {
        if (messageHistory) {
            messageHistory.delete flush: true
            request.withFormat {
                form {
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'MessageHistory.label', default: 'MessageHistory'), messageHistory.id])
                    redirect action: "index", method: "GET"
                }
                '*' { render status: NO_CONTENT }
            }
        } else {
            render status: NOT_FOUND
        }
    }
}

Chat/grails-app/views/messageHistory/_form.gsp
<%@ page import="com.youniversity.apps.chat.MessageHistory" %>



<div class="fieldcontain ${hasErrors(bean: messageHistory, field: 'text', 'error')} ">
	<label for="text">
		<g:message code="messageHistory.text.label" default="Text" />
		
	</label>
	<g:textArea name="text" cols="40" rows="5" maxlength="20000" value="${messageHistory?.text}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: messageHistory, field: 'lastEdited', 'error')} ">
	<label for="lastEdited">
		<g:message code="messageHistory.lastEdited.label" default="Last Edited" />
		
	</label>
	<g:datePicker name="lastEdited" precision="day"  value="${messageHistory?.lastEdited}" default="none" noSelection="['': '']" />
</div>

<div class="fieldcontain ${hasErrors(bean: messageHistory, field: 'message', 'error')} required">
	<label for="message">
		<g:message code="messageHistory.message.label" default="Message" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="message" name="message.id" from="${com.youniversity.apps.chat.Message.list()}" optionKey="id" required="" value="${messageHistory?.message?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: messageHistory, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="messageHistory.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="user" type="number" value="${messageHistory.user}" required=""/>
</div>

Chat/grails-app/views/messageHistory/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'messageHistory.label', default: 'MessageHistory')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-messageHistory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-messageHistory" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${messageHistory}">
			<ul class="errors" role="alert">
				<g:eachError bean="${messageHistory}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:messageHistory, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Chat/grails-app/views/messageHistory/edit.gsp
<%@ page import="com.youniversity.apps.chat.MessageHistory" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'messageHistory.label', default: 'MessageHistory')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-messageHistory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-messageHistory" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${messageHistory}">
			<ul class="errors" role="alert">
				<g:eachError bean="${messageHistory}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:messageHistory, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${messageHistory?.version}" />				
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Chat/grails-app/views/messageHistory/index.gsp
<%@ page import="com.youniversity.apps.chat.MessageHistory" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'messageHistory.label', default: 'MessageHistory')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-messageHistory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-messageHistory" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="text" title="${message(code: 'messageHistory.text.label', default: 'Text')}" />
					
						<g:sortableColumn property="lastEdited" title="${message(code: 'messageHistory.lastEdited.label', default: 'Last Edited')}" />
					
						<th><g:message code="messageHistory.message.label" default="Message" /></th>
					
						<g:sortableColumn property="user" title="${message(code: 'messageHistory.user.label', default: 'User')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${messageHistoryList}" status="i" var="messageHistory">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${messageHistory.id}">${fieldValue(bean: messageHistory, field: "text")}</g:link></td>
					
						<td><g:formatDate date="${messageHistory.lastEdited}" /></td>
					
						<td>${fieldValue(bean: messageHistory, field: "message")}</td>
					
						<td>${fieldValue(bean: messageHistory, field: "user")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${messageHistoryCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Chat/grails-app/views/messageHistory/show.gsp
<%@ page import="com.youniversity.apps.chat.MessageHistory" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'messageHistory.label', default: 'MessageHistory')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-messageHistory" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-messageHistory" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list messageHistory">
			
				<g:if test="${messageHistory?.text}">
				<li class="fieldcontain">
					<span id="text-label" class="property-label"><g:message code="messageHistory.text.label" default="Text" /></span>
					
						<span class="property-value" aria-labelledby="text-label"><g:fieldValue bean="${messageHistory}" field="text"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${messageHistory?.lastEdited}">
				<li class="fieldcontain">
					<span id="lastEdited-label" class="property-label"><g:message code="messageHistory.lastEdited.label" default="Last Edited" /></span>
					
						<span class="property-value" aria-labelledby="lastEdited-label"><g:formatDate date="${messageHistory?.lastEdited}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${messageHistory?.message}">
				<li class="fieldcontain">
					<span id="message-label" class="property-label"><g:message code="messageHistory.message.label" default="Message" /></span>
					
						<span class="property-value" aria-labelledby="message-label"><g:link controller="message" action="show" id="${messageHistory?.message?.id}">${messageHistory?.message?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${messageHistory?.user}">
				<li class="fieldcontain">
					<span id="user-label" class="property-label"><g:message code="messageHistory.user.label" default="User" /></span>
					
						<span class="property-value" aria-labelledby="user-label"><g:fieldValue bean="${messageHistory}" field="user"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:messageHistory, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${messageHistory}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>